<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  {{extension.element.lower}}
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;

JHtmlBootstrap::tooltip();

/**
 * Prepare data for this template.
 *
 * @var $container Windwalker\DI\Container
 * @var $data      Windwalker\Data\Data
 * @var $state     Joomla\Registry\Registry
 * @var $user      \JUser
 */
$container = $this->getContainer();
$data      = $this->data;
$state     = $data->state;
$user      = $container->get('user');
$userId    = $user->get('id');

$listOrder = $state->get('list.ordering');
$listDirn  = $state->get('list.direction');
$canOrder  = $user->authorise('core.edit.state', '{{extension.element.lower}}');
$saveOrder = $listOrder == 'a.ordering';
?>
<form action="<?php echo JRoute::_('index.php?option={{extension.element.lower}}&view={{controller.list.name.lower}}'); ?>" method="post" name="adminForm" id="adminForm">

	<div id="{{extension.name.lower}}-wrap" class="windwalker list container-fluid {{controller.list.name.lower}}<?php echo $data->params->get('pageclass_sfx'); ?>">
		<div id="{{extension.name.lower}}-wrap-inner">

			<!-- Heading -->
			<?php if ($data->params->get('show_page_heading', 1)) : ?>
				<h1>
					<?php echo $this->escape($data->params->get('page_heading')); ?>
				</h1>
			<?php endif; ?>

			<?php if ($data->params->get('show_category_title') or $data->params->get('page_subheading')) : ?>
				<h2>
					<?php echo $this->escape($data->params->get('page_subheading')); ?>
					<?php if ($data->params->get('show_category_title')) : ?>
						<span class="subheading-category"><?php echo $this->escape($data->category->title); ?></span>
					<?php endif; ?>
				</h2>
			<?php endif; ?>
			<!-- Heading End -->

		</div>
	</div>

	<div>
		<input type="hidden" name="task" value="" />
		<input type="hidden" name="boxchecked" value="0" />
		<input type="hidden" name="filter_order" value="<?php echo $listOrder; ?>" />
		<input type="hidden" name="filter_order_Dir" value="<?php echo $listDirn; ?>" />
		<input type="hidden" name="return" id="return_url" value="<?php echo base64_encode(JFactory::getURI()->toString()); ?>" />
		<?php echo JHtml::_('form.token'); ?>
	</div>

</form>